---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: nsm-system

bases:
- https://github.com/networkservicemesh/deployments-k8s/apps/nsmgr?ref=40eba2b9d535b7e3c0e3f7463af6227d863c5a32
- https://github.com/networkservicemesh/deployments-k8s/apps/forwarder-vpp?ref=40eba2b9d535b7e3c0e3f7463af6227d863c5a32
- https://github.com/networkservicemesh/deployments-k8s/apps/registry-k8s?ref=40eba2b9d535b7e3c0e3f7463af6227d863c5a32
- https://github.com/networkservicemesh/deployments-k8s/apps/registry-proxy-dns?ref=40eba2b9d535b7e3c0e3f7463af6227d863c5a32
- https://github.com/networkservicemesh/deployments-k8s/apps/nsmgr-proxy?ref=40eba2b9d535b7e3c0e3f7463af6227d863c5a32
- ../../../../apps/admission-webhook-k8s

resources:
  - namespace.yaml

patchesStrategicMerge:
- patch-nsmgr-proxy.yaml
- patch-registry-proxy-dns.yaml
- patch-registry.yaml
