---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: nsm-system

bases:
- https://github.com/networkservicemesh/deployments-k8s/apps/cluster-info?ref=170cc17149054a1bbca91f6e8c2d08d6b797e525
- https://github.com/kubernetes-sigs/about-api/clusterproperty/config/crd?ref=170cc17149054a1bbca91f6e8c2d08d6b797e525
- ../../../../apps/nsmgr
- ../../../../apps/forwarder-vpp
- ../../../../apps/registry-memory
- ../../../../apps/registry-proxy-dns
- ../../../../apps/nsmgr-proxy

resources:
  - "cluster-property.yaml"

patchesStrategicMerge:
- patch-nsmgr-proxy.yaml
- patch-registry-proxy-dns.yaml
- patch-registry-memory.yaml
