---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: ns-annotated-namespace

resources:
  - netsvc.yaml
  - namespace.yaml

bases:
  - https://github.com/networkservicemesh/deployments-k8s/apps/nse-kernel?ref=c2e01a9dd3f2f87ea07074dc361b06a39384e6d6

patchesStrategicMerge:
  - patch-nse.yaml
