---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: ns-annotated-namespace

resources:
  - netsvc.yaml
  - namespace.yaml

bases:
  - https://github.com/networkservicemesh/deployments-k8s/apps/nse-kernel?ref=8a514e1d85c4d22e27b2f744cada54cae00a9a63

patchesStrategicMerge:
  - patch-nse.yaml
