---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: nsm-system

resources:
- namespace.yaml
- ../../../../apps/nsmgr
- ../../../../apps/forwarder-vpp
- ../../../../apps/registry-k8s
- ../../../../apps/registry-proxy-dns
- ../../../../apps/nsmgr-proxy
- ../../../../apps/admission-webhook-k8s

patches:
 - path: patch-nsmgr-proxy.yaml
 - path: patch-registry-proxy-dns.yaml
 - path: patch-registry.yaml
 - target:
      version: v1
      kind: Service
      name: registry
   path: patch-registry-service.yaml
