---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: nsm-system

bases:
- https://github.com/networkservicemesh/deployments-k8s/apps/nsmgr?ref=3753be20a2ef1a9705d29d8219b48ec4a620c8ec
- https://github.com/networkservicemesh/deployments-k8s/apps/forwarder-vpp?ref=3753be20a2ef1a9705d29d8219b48ec4a620c8ec
- https://github.com/networkservicemesh/deployments-k8s/apps/registry-k8s?ref=3753be20a2ef1a9705d29d8219b48ec4a620c8ec
- https://github.com/networkservicemesh/deployments-k8s/apps/registry-proxy-dns?ref=3753be20a2ef1a9705d29d8219b48ec4a620c8ec
- https://github.com/networkservicemesh/deployments-k8s/apps/nsmgr-proxy?ref=3753be20a2ef1a9705d29d8219b48ec4a620c8ec
- https://github.com/networkservicemesh/deployments-k8s/apps/admission-webhook-k8s?ref=3753be20a2ef1a9705d29d8219b48ec4a620c8ec

patchesStrategicMerge:
- patch-nsmgr-proxy.yaml
- patch-registry-proxy-dns.yaml
- patch-registry.yaml

resources:
  - namespace.yaml
