---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: nsm-system

bases:
- https://github.com/networkservicemesh/deployments-k8s/apps/nsmgr?ref=8684eeab1df8c5be333664c1ba8cd1680a4e7451
- https://github.com/networkservicemesh/deployments-k8s/apps/forwarder-vpp?ref=8684eeab1df8c5be333664c1ba8cd1680a4e7451
- https://github.com/networkservicemesh/deployments-k8s/apps/registry-k8s?ref=8684eeab1df8c5be333664c1ba8cd1680a4e7451
- https://github.com/networkservicemesh/deployments-k8s/apps/registry-proxy-dns?ref=8684eeab1df8c5be333664c1ba8cd1680a4e7451
- https://github.com/networkservicemesh/deployments-k8s/apps/nsmgr-proxy?ref=8684eeab1df8c5be333664c1ba8cd1680a4e7451
- https://github.com/networkservicemesh/deployments-k8s/apps/admission-webhook-k8s?ref=8684eeab1df8c5be333664c1ba8cd1680a4e7451

patchesStrategicMerge:
- patch-nsmgr-proxy.yaml
- patch-registry-proxy-dns.yaml
- patch-registry.yaml

resources:
  - namespace.yaml
