---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: ns-dns-vl3

bases:
- https://github.com/networkservicemesh/deployments-k8s/apps/nse-vl3-vpp?ref=51e746f64f79ffbaad5f1095db126db94a48d57e
- https://github.com/networkservicemesh/deployments-k8s/apps/vl3-ipam?ref=51e746f64f79ffbaad5f1095db126db94a48d57e

resources:
- namespace.yaml

patchesStrategicMerge:
- nse-patch.yaml
