---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: ns-dns-vl3

bases:
- https://github.com/networkservicemesh/deployments-k8s/apps/nse-vl3-vpp?ref=bf472f8b9457301ba27fccd49609cff49225a9e8
- https://github.com/networkservicemesh/deployments-k8s/apps/vl3-ipam?ref=bf472f8b9457301ba27fccd49609cff49225a9e8

resources:
- namespace.yaml

patchesStrategicMerge:
- nse-patch.yaml
