---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: ns-dns-vl3

bases:
- https://github.com/networkservicemesh/deployments-k8s/apps/nse-vl3-vpp?ref=e56efec1d2695f26c87e1420a9d69afca8b7248d
- https://github.com/networkservicemesh/deployments-k8s/apps/vl3-ipam?ref=e56efec1d2695f26c87e1420a9d69afca8b7248d

resources:
- namespace.yaml

patchesStrategicMerge:
- nse-patch.yaml
