---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: ns-dns-vl3

bases:
- https://github.com/networkservicemesh/deployments-k8s/apps/nse-vl3-vpp?ref=8a8310da80d04274bf9834426d73b055a4c53198
- https://github.com/networkservicemesh/deployments-k8s/apps/vl3-ipam?ref=8a8310da80d04274bf9834426d73b055a4c53198

resources:
- namespace.yaml

patchesStrategicMerge:
- nse-patch.yaml
