---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: nsm-system

bases:
  - https://github.com/networkservicemesh/deployments-k8s/apps/forwarder-vpp?ref=77384670352f0c761ff0e7db6ce6eef8196f78ae

configMapGenerator:
  - name: device-selector
    files:
      - selector
patchesStrategicMerge:
  - patch-forwarder-vpp.yaml
