---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: nsm-system

bases:
  - https://github.com/networkservicemesh/deployments-k8s/apps/forwarder-vpp?ref=8a7a76dbe9267313397e7e59d6c9fb457de3a285

configMapGenerator:
  - name: device-selector
    files:
      - selector
patchesStrategicMerge:
  - patch-forwarder-vpp.yaml
