---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: nsm-system

bases:
  - https://github.com/networkservicemesh/deployments-k8s/apps/forwarder-vpp?ref=c0dd05e3b6fc40722ea82ebb33bcb5591bb15301

configMapGenerator:
  - name: device-selector
    files:
      - selector
patchesStrategicMerge:
  - patch-forwarder-vpp.yaml
