---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: nsm-system

resources:
  - netsvc.yaml
  - ../../../../../apps/vl3-ipam

patchesStrategicMerge:
- patch-vl3-ipam.yaml

patches:
 - target:
      version: v1
      kind: Service
      name: vl3-ipam
   path: patch-ipam-service.yaml