---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

bases:
- https://github.com/networkservicemesh/deployments-k8s/apps/nse-supplier-k8s?ref=a02c5fbf856d7d5d46f7456c6f32389be0350b06

patchesStrategicMerge:
- patch-supplier.yaml

configMapGenerator:
  - name: supplier-pod-template-configmap-server
    files:
      - pod-template.yaml
  - name: iptables-map
    files:
      - iptables-map.yaml

generatorOptions:
  disableNameSuffixHash: true
