---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

bases:
- https://github.com/networkservicemesh/deployments-k8s/apps/nse-supplier-k8s?ref=532876ac220e926fa1bac0fb379739de1ac94aaf

patchesStrategicMerge:
- patch-supplier.yaml

configMapGenerator:
  - name: supplier-pod-template-configmap
    files:
      - pod-template.yaml
  - name: iptables-map
    files:
      - iptables-map.yaml

generatorOptions:
  disableNameSuffixHash: true
