---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

bases:
- https://github.com/networkservicemesh/deployments-k8s/apps/nse-supplier-k8s?ref=ca98aa7262f383d65654615ac6196c31ae26406f

patchesStrategicMerge:
- patch-supplier.yaml

configMapGenerator:
  - name: supplier-pod-template-configmap
    files:
      - pod-template.yaml
  - name: iptables-map
    files:
      - iptables-map.yaml

generatorOptions:
  disableNameSuffixHash: true
