---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

bases:
- https://github.com/networkservicemesh/deployments-k8s/apps/nse-supplier-k8s?ref=058c7123970bf634908601616f893e2b05635890

patchesStrategicMerge:
- patch-supplier.yaml

configMapGenerator:
  - name: supplier-pod-template-configmap
    files:
      - pod-template.yaml
  - name: iptables-map
    files:
      - iptables-map.yaml

generatorOptions:
  disableNameSuffixHash: true
