---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: nsm-system

bases:
- https://github.com/networkservicemesh/deployments-k8s/apps/nsmgr?ref=0ac829aa1b4f728538deb225f716882479888fbb
- https://github.com/networkservicemesh/deployments-k8s/apps/forwarder-vpp?ref=0ac829aa1b4f728538deb225f716882479888fbb
- https://github.com/networkservicemesh/deployments-k8s/apps/registry-k8s?ref=0ac829aa1b4f728538deb225f716882479888fbb
- https://github.com/networkservicemesh/deployments-k8s/apps/registry-proxy-dns?ref=0ac829aa1b4f728538deb225f716882479888fbb
- https://github.com/networkservicemesh/deployments-k8s/apps/nsmgr-proxy?ref=0ac829aa1b4f728538deb225f716882479888fbb
- https://github.com/networkservicemesh/deployments-k8s/apps/admission-webhook-k8s?ref=0ac829aa1b4f728538deb225f716882479888fbb

patchesStrategicMerge:
- patch-nsmgr-proxy.yaml
- patch-registry-proxy-dns.yaml
- patch-registry.yaml

resources:
  - namespace.yaml
