---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: ns-mutually-aware-nses

bases:
- https://github.com/networkservicemesh/deployments-k8s/apps/nsc-kernel?ref=ba172266838eade1df97e2a8479fc73c3a9563c0

resources:
- nse-1.yaml
- nse-2.yaml
- netsvc-1.yaml
- netsvc-2.yaml
- config-file-nse-1.yaml
- config-file-nse-2.yaml

patchesStrategicMerge:
- patch-nsc.yaml
