---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: spire

configMapGenerator:
- name: spire-server
  behavior: merge
  namespace: spire
  files:
  - server.conf
- name: spire-agent
  behavior: merge
  namespace: spire
  files:
  - agent.conf
- name: k8s-workload-registrar
  behavior: merge
  namespace: spire
  files:
    - k8s-workload-registrar.conf


bases:
- https://github.com/networkservicemesh/deployments-k8s/examples/spire?ref=b871cdeb969e6f5bfc78b6abd6bd5e11507bfbbd
