---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: nsm-system

bases:
- https://github.com/networkservicemesh/deployments-k8s/apps/cluster-info?ref=8c24b50eb5a082fe5a6d2de5f4ce2d52004644e0
- https://github.com/kubernetes-sigs/about-api/clusterproperty/config/crd?ref=8c24b50eb5a082fe5a6d2de5f4ce2d52004644e0
- ../../../../apps/nsmgr
- ../../../../apps/forwarder-vpp
- ../../../../apps/registry-memory
- ../../../../apps/registry-proxy-dns
- ../../../../apps/nsmgr-proxy

resources:
  - "cluster-property.yaml"

patchesStrategicMerge:
- patch-nsmgr-proxy.yaml
- patch-registry-proxy-dns.yaml
- patch-registry-memory.yaml
