---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: ns-vl3

bases:
- https://github.com/networkservicemesh/deployments-k8s/apps/nsc-kernel?ref=8d0b4154088dbdaf276ba5ca1fa3e107e50c872e
- https://github.com/networkservicemesh/deployments-k8s/apps/nse-vl3-vpp?ref=8d0b4154088dbdaf276ba5ca1fa3e107e50c872e
- https://github.com/networkservicemesh/deployments-k8s/apps/vl3-ipam?ref=8d0b4154088dbdaf276ba5ca1fa3e107e50c872e

patchesStrategicMerge:
- https://raw.githubusercontent.com/networkservicemesh/deployments-k8s/8d0b4154088dbdaf276ba5ca1fa3e107e50c872e/examples/features/vl3-basic/nsc-patch.yaml
- https://raw.githubusercontent.com/networkservicemesh/deployments-k8s/8d0b4154088dbdaf276ba5ca1fa3e107e50c872e/examples/features/vl3-basic/nse-patch.yaml
