---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: ns-vl3

resources:
  - ../../../examples/features/vl3-basic/vl3-netsvc.yaml

bases:
- https://github.com/networkservicemesh/deployments-k8s/apps/nsc-kernel?ref=a2c7c850f432fd70e320b7c50f58f00a63f6c6c2
- https://github.com/networkservicemesh/deployments-k8s/apps/nse-vl3-vpp?ref=a2c7c850f432fd70e320b7c50f58f00a63f6c6c2
- https://github.com/networkservicemesh/deployments-k8s/apps/vl3-ipam?ref=a2c7c850f432fd70e320b7c50f58f00a63f6c6c2

patchesStrategicMerge:
- https://raw.githubusercontent.com/networkservicemesh/deployments-k8s/a2c7c850f432fd70e320b7c50f58f00a63f6c6c2/examples/features/vl3-basic/nsc-patch.yaml
- https://raw.githubusercontent.com/networkservicemesh/deployments-k8s/a2c7c850f432fd70e320b7c50f58f00a63f6c6c2/examples/features/vl3-basic/nse-patch.yaml
