---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: ns-vl3

bases:
- https://github.com/networkservicemesh/deployments-k8s/apps/nsc-kernel?ref=5878faef14b4c99d3e960440194991f77b2d07c7
- https://github.com/networkservicemesh/deployments-k8s/apps/nse-vl3-vpp?ref=5878faef14b4c99d3e960440194991f77b2d07c7
- https://github.com/networkservicemesh/deployments-k8s/apps/vl3-ipam?ref=5878faef14b4c99d3e960440194991f77b2d07c7

resources:
- https://raw.githubusercontent.com/networkservicemesh/deployments-k8s/5878faef14b4c99d3e960440194991f77b2d07c7/examples/features/vl3-basic/vl3-netsvc.yaml

patchesStrategicMerge:
- https://raw.githubusercontent.com/networkservicemesh/deployments-k8s/5878faef14b4c99d3e960440194991f77b2d07c7/examples/features/vl3-basic/nsc-patch.yaml
- https://raw.githubusercontent.com/networkservicemesh/deployments-k8s/5878faef14b4c99d3e960440194991f77b2d07c7/examples/features/vl3-basic/nse-patch.yaml
