---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: ns-vl3

bases:
- https://github.com/networkservicemesh/deployments-k8s/apps/nsc-kernel?ref=98ecb52bf8675c68307f8d61c7ce4aa28970f100
- https://github.com/networkservicemesh/deployments-k8s/apps/nse-vl3-vpp?ref=98ecb52bf8675c68307f8d61c7ce4aa28970f100
- https://github.com/networkservicemesh/deployments-k8s/apps/vl3-ipam?ref=98ecb52bf8675c68307f8d61c7ce4aa28970f100

resources:
- https://raw.githubusercontent.com/networkservicemesh/deployments-k8s/98ecb52bf8675c68307f8d61c7ce4aa28970f100/examples/features/vl3-basic/vl3-netsvc.yaml

patchesStrategicMerge:
- https://raw.githubusercontent.com/networkservicemesh/deployments-k8s/98ecb52bf8675c68307f8d61c7ce4aa28970f100/examples/features/vl3-basic/nsc-patch.yaml
- https://raw.githubusercontent.com/networkservicemesh/deployments-k8s/98ecb52bf8675c68307f8d61c7ce4aa28970f100/examples/features/vl3-basic/nse-patch.yaml
