---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: ns-vl3

bases:
- https://github.com/networkservicemesh/deployments-k8s/apps/nsc-kernel?ref=481fa91bcd8836fe4682c85110d3d12339aec507
- https://github.com/networkservicemesh/deployments-k8s/apps/nse-vl3-vpp?ref=481fa91bcd8836fe4682c85110d3d12339aec507
- https://github.com/networkservicemesh/deployments-k8s/apps/vl3-ipam?ref=481fa91bcd8836fe4682c85110d3d12339aec507

resources:
- https://raw.githubusercontent.com/networkservicemesh/deployments-k8s/481fa91bcd8836fe4682c85110d3d12339aec507/examples/features/vl3-basic/vl3-netsvc.yaml

patchesStrategicMerge:
- https://raw.githubusercontent.com/networkservicemesh/deployments-k8s/481fa91bcd8836fe4682c85110d3d12339aec507/examples/features/vl3-basic/nsc-patch.yaml
- https://raw.githubusercontent.com/networkservicemesh/deployments-k8s/481fa91bcd8836fe4682c85110d3d12339aec507/examples/features/vl3-basic/nse-patch.yaml
