---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: ns-vl3

bases:
- https://github.com/networkservicemesh/deployments-k8s/apps/nsc-kernel?ref=a0958ce14e46273bce5e9f5fd74289ea8be80560
- https://github.com/networkservicemesh/deployments-k8s/apps/nse-vl3-vpp?ref=a0958ce14e46273bce5e9f5fd74289ea8be80560
- https://github.com/networkservicemesh/deployments-k8s/apps/vl3-ipam?ref=a0958ce14e46273bce5e9f5fd74289ea8be80560

patchesStrategicMerge:
- https://raw.githubusercontent.com/networkservicemesh/deployments-k8s/a0958ce14e46273bce5e9f5fd74289ea8be80560/examples/features/vl3-basic/nsc-patch.yaml
- https://raw.githubusercontent.com/networkservicemesh/deployments-k8s/a0958ce14e46273bce5e9f5fd74289ea8be80560/examples/features/vl3-basic/nse-patch.yaml
