---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: ns-exclude-prefixes-client

resources:
- ns-exclude-prefixes-client.yaml
- client.yaml
- nsm-service-1.yaml
- nsm-service-2.yaml
- nse-kernel-1.yaml
- nse-kernel-2.yaml
