---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: ns-jaeger-and-prometheus

resources:
- client.yaml
- netsvc.yaml

bases:
- https://github.com/networkservicemesh/deployments-k8s/apps/nse-kernel?ref=dcfff3a876ea114d67f9daddc6d09cc2b8c28a51

patchesStrategicMerge:
- patch-nse.yaml
