---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: ns-jaeger-and-prometheus

resources:
- ns-jaeger-and-prometheus.yaml
- client.yaml
- netsvc.yaml

bases:
- https://github.com/networkservicemesh/deployments-k8s/apps/nse-kernel?ref=71568f0198ba6ef42dc30e8b2fac85fdd64a8004

patchesStrategicMerge:
- patch-nse.yaml
