---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nse-kernel
spec:
  template:
    spec:
      containers:
        - name: nse
          env:
            - name: NSM_CIDR_PREFIX
              value: 172.16.1.100/31
            - name: TELEMETRY
              value: "true"
            - name: NSM_SERVICE_NAMES
              value: "jaeger-and-prometheus"
            - name: NSM_REGISTER_SERVICE
              value: "false"