---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

bases:
- https://github.com/networkservicemesh/deployments-k8s/apps/nse-supplier-k8s?ref=81ee293f21651f6509d8e457212fafb4fc250e9e

patchesStrategicMerge:
- patch-supplier.yaml

configMapGenerator:
  - name: supplier-pod-template-configmap
    files:
      - pod-template.yaml

generatorOptions:
  disableNameSuffixHash: true
