---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: ns-exclude-prefixes

resources:
- ns-exclude-prefixes.yaml
- netsvc.yaml
- client.yaml
- ../../../apps/nse-kernel

patchesStrategicMerge:
- patch-nse.yaml
