---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: ns-dns-vl3

bases:
- https://github.com/networkservicemesh/deployments-k8s/apps/nse-vl3-vpp?ref=6cb851e2075646d8476d01f4f881a9a27b80f507
- https://github.com/networkservicemesh/deployments-k8s/apps/vl3-ipam?ref=6cb851e2075646d8476d01f4f881a9a27b80f507

resources:
- https://raw.githubusercontent.com/networkservicemesh/deployments-k8s/6cb851e2075646d8476d01f4f881a9a27b80f507/examples/features/vl3-dns/nsc.yaml
- https://raw.githubusercontent.com/networkservicemesh/deployments-k8s/6cb851e2075646d8476d01f4f881a9a27b80f507/examples/features/vl3-dns/namespace.yaml
- https://raw.githubusercontent.com/networkservicemesh/deployments-k8s/6cb851e2075646d8476d01f4f881a9a27b80f507/examples/features/vl3-dns/vl3-netsvc.yaml

patchesStrategicMerge:
- https://raw.githubusercontent.com/networkservicemesh/deployments-k8s/6cb851e2075646d8476d01f4f881a9a27b80f507/examples/features/vl3-dns/nse-patch.yaml
