---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: ns-dns-vl3

bases:
- https://github.com/networkservicemesh/deployments-k8s/apps/nse-vl3-vpp?ref=4005f448fd71c449c9d03b60d3e0d4efa372111a
- https://github.com/networkservicemesh/deployments-k8s/apps/vl3-ipam?ref=4005f448fd71c449c9d03b60d3e0d4efa372111a

resources:
- https://raw.githubusercontent.com/networkservicemesh/deployments-k8s/4005f448fd71c449c9d03b60d3e0d4efa372111a/examples/features/vl3-dns/nsc.yaml
- https://raw.githubusercontent.com/networkservicemesh/deployments-k8s/4005f448fd71c449c9d03b60d3e0d4efa372111a/examples/features/vl3-dns/namespace.yaml

patchesStrategicMerge:
- https://raw.githubusercontent.com/networkservicemesh/deployments-k8s/4005f448fd71c449c9d03b60d3e0d4efa372111a/examples/features/vl3-dns/nse-patch.yaml
