---
services:
  nse-simple-vl3-docker:
    image: ghcr.io/networkservicemesh/cmd-nse-simple-vl3-docker:v1.7.0-rc.2
    privileged: true
    container_name: nse-simple-vl3-docker
    restart: always
    environment:
      NSM_NAME: docker-vl3-server@k8s.nsm
      NSM_SERVICE_NAMES: docker-vl3@k8s.nsm
      NSM_CONNECT_TO: tcp://k8s.nsm
      NSM_FEDERATES_WITH: k8s.nsm
      NSM_TRUST_DOMAIN: docker.nsm
      NSM_LOG_LEVEL: TRACE
