
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nse-firewall-vpp
spec:
  template:
    spec:
      containers:
        - name: nse
          volumeMounts:
            - mountPath: /etc/vppagent-firewall/config.yaml
              subPath: config.yaml
              name: vppagent-firewall-config-volume
      volumes:
        - name: vppagent-firewall-config-volume
          configMap:
            name: vppagent-firewall-config-file