---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: ns-vl3

resources:
- https://raw.githubusercontent.com/networkservicemesh/deployments-k8s/7758662e8a91c411ed8740e9f76c3c921d87d321/examples/features/vl3-scale-from-zero/autoscale-netsvc.yaml
- https://raw.githubusercontent.com/networkservicemesh/deployments-k8s/7758662e8a91c411ed8740e9f76c3c921d87d321/examples/features/vl3-scale-from-zero/vl3-netsvc.yaml

bases:
- https://github.com/networkservicemesh/deployments-k8s/apps/nsc-kernel?ref=7758662e8a91c411ed8740e9f76c3c921d87d321
- https://github.com/networkservicemesh/deployments-k8s/apps/vl3-ipam?ref=7758662e8a91c411ed8740e9f76c3c921d87d321
- https://github.com/networkservicemesh/deployments-k8s/apps/nse-supplier-k8s?ref=7758662e8a91c411ed8740e9f76c3c921d87d321

patchesStrategicMerge:
- nsc-patch.yaml
- supplier-patch.yaml

configMapGenerator:
  - name: supplier-pod-template-configmap
    files:
      - https://raw.githubusercontent.com/networkservicemesh/deployments-k8s/7758662e8a91c411ed8740e9f76c3c921d87d321/examples/features/vl3-scale-from-zero/pod-template.yaml
