---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: ns-vl3

resources:
- https://raw.githubusercontent.com/networkservicemesh/deployments-k8s/e283eb63593c14fd7b92d8d098da87e6121ef314/examples/features/vl3-scale-from-zero/autoscale-netsvc.yaml
- https://raw.githubusercontent.com/networkservicemesh/deployments-k8s/e283eb63593c14fd7b92d8d098da87e6121ef314/examples/features/vl3-scale-from-zero/vl3-netsvc.yaml

bases:
- https://github.com/networkservicemesh/deployments-k8s/apps/nsc-kernel?ref=e283eb63593c14fd7b92d8d098da87e6121ef314
- https://github.com/networkservicemesh/deployments-k8s/apps/vl3-ipam?ref=e283eb63593c14fd7b92d8d098da87e6121ef314
- https://github.com/networkservicemesh/deployments-k8s/apps/nse-supplier-k8s?ref=e283eb63593c14fd7b92d8d098da87e6121ef314

patchesStrategicMerge:
- nsc-patch.yaml
- supplier-patch.yaml

configMapGenerator:
  - name: supplier-pod-template-configmap
    files:
      - https://raw.githubusercontent.com/networkservicemesh/deployments-k8s/e283eb63593c14fd7b92d8d098da87e6121ef314/examples/features/vl3-scale-from-zero/pod-template.yaml
