---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: ns-vl3

resources:
- https://raw.githubusercontent.com/networkservicemesh/deployments-k8s/1cbd147331203210a78968a0000fd33e29b8ea92/examples/features/vl3-scale-from-zero/autoscale-netsvc.yaml
- https://raw.githubusercontent.com/networkservicemesh/deployments-k8s/1cbd147331203210a78968a0000fd33e29b8ea92/examples/features/vl3-scale-from-zero/vl3-netsvc.yaml

bases:
- https://github.com/networkservicemesh/deployments-k8s/apps/nsc-kernel?ref=1cbd147331203210a78968a0000fd33e29b8ea92
- https://github.com/networkservicemesh/deployments-k8s/apps/vl3-ipam?ref=1cbd147331203210a78968a0000fd33e29b8ea92
- https://github.com/networkservicemesh/deployments-k8s/apps/nse-supplier-k8s?ref=1cbd147331203210a78968a0000fd33e29b8ea92

patchesStrategicMerge:
- nsc-patch.yaml
- supplier-patch.yaml

configMapGenerator:
  - name: supplier-pod-template-configmap
    files:
      - https://raw.githubusercontent.com/networkservicemesh/deployments-k8s/1cbd147331203210a78968a0000fd33e29b8ea92/examples/features/vl3-scale-from-zero/pod-template.yaml
