---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: ns-kernel2ip2kernel

resources:
- ns-kernel2ip2kernel.yaml
- client.yaml
- netsvc.yaml
- ../../../apps/nse-kernel

patchesStrategicMerge:
- patch-nse.yaml
