---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: ns-remote-forwarder-death-ip

resources:
- ns-remote-forwarder-death-ip.yaml
- netsvc.yaml
- client.yaml
- ../../../apps/nse-kernel

patchesStrategicMerge:
- patch-nse.yaml
