---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: nsm-system

bases:
  - https://github.com/networkservicemesh/deployments-k8s/apps/forwarder-ovs?ref=7aff6580aa85e509e3844c536d11475de4c16ba7

configMapGenerator:
  - name: device-selector
    files:
      - selector

patchesStrategicMerge:
  - patch-forwarder-ovs.yaml
