---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: nsm-system

bases:
  - https://github.com/networkservicemesh/deployments-k8s/apps/forwarder-ovs?ref=9dd26724571780bb7cb3d7eb760175439613c71c

configMapGenerator:
  - name: device-selector
    files:
      - selector

patchesStrategicMerge:
  - patch-forwarder-ovs.yaml
