---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: nsm-system

bases:
  - https://github.com/networkservicemesh/deployments-k8s/apps/forwarder-ovs?ref=d840c52896fcd86dece89013ef9afc100b6775a0

configMapGenerator:
  - name: device-selector
    files:
      - selector

patchesStrategicMerge:
  - patch-forwarder-ovs.yaml
