---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: nsm-system

bases:
  - https://github.com/networkservicemesh/deployments-k8s/apps/forwarder-ovs?ref=cd5d49e78defd5d5c3dcfa2df58f44e67defabea

configMapGenerator:
  - name: device-selector
    files:
      - selector

patchesStrategicMerge:
  - patch-forwarder-ovs.yaml
