---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: nsm-system

bases:
  - https://github.com/networkservicemesh/deployments-k8s/apps/forwarder-ovs?ref=9ce2f3429533f1d7c17efa8be7698b9c9e53a178

configMapGenerator:
  - name: device-selector
    files:
      - selector

patchesStrategicMerge:
  - patch-forwarder-ovs.yaml
