---
apiVersion: v1
kind: ConfigMap
metadata:
  name: policies-config-file-2
data:
  config.yaml: |
    - from: 172.16.1.101/32
      proto: 6
      port: 5555
      routes:
        - prefix: 172.16.1.100/32
  
