---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: ns-floating-kernel2ethernet2memif

resources:
- ns-floating-kernel2ethernet2memif.yaml
- ../../../../../apps/nse-memif

patchesStrategicMerge:
- patch-nse.yaml
